arikkfir-org/greenstar

frontend/Dockerfile
frontend/Dockerfile.debug
frontend/fix-growthbook-package-json.sh

This change ensures the frontend container images patch & fix the bug in the Growthbook package, that exports incorrect Typescript bindings.

fix(frontend): patch the Growthbook typescript bindings bug

---

deploy/cluster/kustomization.yaml

This change patches IngressRoute and IngressRouteTCP objects to use the "ip-whitelist" or "ip-whitelist-tcp" middleware, which will ensure that Traefik restricts traffic accordingly.

fix(deploy): restrict traffic to whitelisted IPs

---

deploy/cluster/kustomization.yaml

This configuration is required to ensure that calls to the backend are only allowed from the application domains.

fix(backend): provide missing HTTP CORS allowed origins

---

deploy/base/app/backend.yaml
deploy/base/app/frontend.yaml
deploy/cluster/gcp-iam.yaml
deploy/cluster/kustomization.yaml
deploy/cluster/secrets.yaml

This change modifies the cluster deployment manifests to mirror Descope GCP secrets into the cluster, and providing them to the backend deployment.

fix(backend): provide missing Descope secrets when running in cluster

---

frontend/src/main.tsx

Do not load the application if it fails inferring the tenant from the URL subdomain.

fix(frontend): fail frontend if tenant cannot be extracted from domain

---

.github/workflows/branch_build.yml

No need to tag container image with PR info - we're building branches only.

chore(ci): remove redundant Docker image tag

---

frontend/nginx.conf

This change ensures that NGINX serves the "index.html" file on missing routes.

fix(frontend): adjust NGINX for HTML5 routing

---

.github/workflows/pr_deploy.yml

Fix a workflow bug causing an incorrect inference of the branch & SHA when triggered by a push event.

fix(ci): Fix ref and SHA inference for push-triggered builds

---

e2e/playwright.config.ts

This is required since we're using Let's Encrypt Staging server for non-main environments.

fix(e2e): ignore TLS certificate errors since we're using LE staging

---

.github/workflows/build.yaml

Current workflow when running for PRs duplicates the comment with the link to test results, instead of updating it.

fix(ci): Fix PR comment duplication

---

Taskfile.yaml

This change deploys the observability stack when running locally.

chore(build): Deploy observability in local dev mode

---

backend/internal/migration/fetch_historical_rates.go

This change adds a missing check for error when creating a transaction.

fix(rates): Fail if transaction cannot be created

---

.idea/modules.xml

There were two modules defined in the JetBrains IDE project, causing duplications and a few minor issues.

chore(ide): Remove redundant module

---

backend/cmd/jobs/init/main.go

Currently, if the ping fails it does not report the error that occurred. This change fixes that.

fix(backend): Report PostgreSQL ping error, if any

---

backend/cmd/jobs/init/main.go
deploy/chart/templates/init-job.tpl.yaml
deploy/chart/values.schema.json
deploy/chart/values.yaml

This change makes the "init-job" component optional, allowing local development of the init-job by running it manually on the workstation instead of in the local cluster.

feat(backend): Allow running the application without the init job

---

backend/cmd/jobs/init/main.go
backend/internal/util/observability/otel_hook.go
deploy/chart/templates/init-job.tpl.yaml
deploy/chart/values.schema.json
deploy/chart/values.yaml

This change fixes the panic that happens when the OTEL SDK is disabled and code is using the `Tracer` field.

fix(backend): Tracer  usage failed when OTEL SDK is disabled

---

.idea/runConfigurations/backend.xml
Taskfile.yaml

This change makes it easier to setup Telepresence on your local workstation for debugging GreenSTAR workloads.

feat(build): Add Telepresence tasks to Taskfile

---

.idea/runConfigurations/backend.xml
Taskfile.yaml

This enables running locally with additional configuration to the Helm chart, if needed (e.g. disable init-job.)

feat(build): Allow adding keys to hack/greenstar-values.yaml

---

.github/workflows/codeql.yml

This change updates the CodeQL configuration to accommodate for the expected language identifiers as expected by the Code scanning merge requirement.

fix(build): Fix CodeQL configuration language IDs

---

backend/cmd/backend/main.go
deploy/chart/templates/frontend.tpl.yaml
deploy/chart/values.schema.json
deploy/chart/values.yaml
deploy/local/chart-local-values.yaml

This change adds support for disabling the pod liveness, readiness & startup probes of the Frontend pod(s), which is necessary during development as the frontend server will be the Vite server rather than the NGINX server used in production.
Thus, instead of implementing health checks in the Vite server (using Express app) this makes it easier by simply disabling these checks when developing locally.

feat(frontend): Allow disabling liveness, readiness & startup probes

---

Taskfile.yaml

This allows running locally without observability, provided one has added "OTEL_SDK_DISABLED" environment variables to the "backend", "initJob" and "exchangeRatesCronJob" workloads with the value "false".
One can modify "hack/greenstar-values.yaml" to do so:
```yaml
...
backend:
extraEnv:
- name: OTEL_SDK_DISABLED
value: "true"
exchangeRatesCronJob:
extraEnv:
- name: OTEL_SDK_DISABLED
value: "true"
initJob:
extraEnv:
- name: OTEL_SDK_DISABLED
value: "true"
```

feat(build): Remove observability dependency from "dev" build task

---

backend/cmd/jobs/init/main.go

This is caused by incorrect assumption for the default value of the (now deleted) "GENERATE_SAMPLE_DATA" flag; boolean values ALWAYS have a default value of "false" (because in the CLI they are just specified as `--my-flag` without any value...).
To fix the issue, this change modifies the flag to be in the negative - by renaming it from `--generate-sample-data` to
`--disable-sample-data-generation`.

fix(backend): Init job does not generate sample data

---

skaffold.yaml

This change fixes the Skaffold pre-deploy hooks by adding the missing quotes and also performing the two patches in one command.

fix(build): Skaffold deployment hooks fail

---

.github/workflows/build.yaml
deploy/chart/templates/backend.tpl.yaml
deploy/chart/templates/exchange-rates-cronjob.tpl.yaml
deploy/chart/templates/frontend.tpl.yaml
deploy/chart/templates/init-job.tpl.yaml
deploy/chart/templates/postgres.tpl.yaml
deploy/chart/values.schema.json
deploy/chart/values.yaml
deploy/local/chart-ci-values.yaml
deploy/local/chart-local-values.yaml
skaffold.yaml

This change modifies the "extraEnv" Helm value of the different workloads from an array of name/value to an object, so that it's possible to override individual environment variables by using multiple Helm values files.
It also disables OTEL SDK in CI environment from the "chart-ci-values.yaml" file instead of the CI workflow.

refactor(build): Support "extraEnv" composition from multiple files

---

backend/internal/server/sample/acme-accounts.yaml

This change fixes some transactions in the sample data set that used the wrong target account. Specifically, the salaries transactions targeted the Bank Of America account instead of the user's primary checking account.
Fixes #225

fix(backend): Incorrect target accounts in some sample data transactions

---

Taskfile.yaml
frontend/src/providers/LocaleProvider.tsx

This change allows the following CLI:
```shell
$ task test -- --headed --timeout=0
```
By utilizing the Taskfile support for CLI args usage in tasks, anything coming after the `--` sign will be passed directly to the `npx playwright test` command.

feat(tests): Support providing CLI args to the `test` task

---

frontend/src/pages/TransactionsPage.tsx

This change fixes the lack of vertical scroll for the accounts tree in the transactions page.

fix(frontend): Accounts Tree in transactions page does not scroll

---

frontend/src/components/table/CustomDataGrid.tsx

This change prevents column dimensions from being saved/loaded from local storage.

feat(frontend): Avoid saving/loading column dimensions in local storage

---

backend/cmd/backend/main.go
backend/cmd/jobs/init/main.go
backend/internal/migration/fetch_currencies.go
backend/internal/migration/fetch_current_rates.go
backend/internal/migration/fetch_historical_rates.go
backend/internal/migration/fetch_missing_rates.go
backend/internal/migration/migrator.go
backend/internal/server/sample/sample_data.go
backend/internal/util/db/pool.go

This change switches uses of the default logger from explicitly referencing it to implicitly referencing it.

chore(backend): Implicitly use the default logger

---

.github/workflows/publish-e2e-results.yaml

Incorrect condition was set for the "Publish E2E Tests Results" workflow which relied on the "outcome" property of the workflow run instead of the "conclusion" property, as the former does not exist for a workflow run.

fix(build): Fix the Publish E2E Tests Results workflow condition

---

.github/workflows/publish-e2e-results.yaml

This change attempts to fix the permissions issue encountered in the "Publish E2E Results" workflow, which can be observed here: https://github.com/arikkfir/greenstar/actions/runs/12514828641/job/34911492790
Unfortunately we cannot test the fix until this change is merged to the `main` branch, given that GitHub runs workflows triggered by the `workflow_run` event from the `main` branch only.
Specifically this change does the following:
- Upgrade the `github-script` action to v7
- Directly pass the workflow's GitHub Token
- Grant the `actions: read` permission to the job

fix(build): Attempt to fix permissions problem in Publish E2E Results workflow

---

.idea/vcs.xml

This is redundant since JetBrains IDEs load GitHub branch protections anyway.

chore(ide): Remove restrictions on 'main' branch from JetBrains settings

---

.github/workflows/codeql.yml

This change modifies the CodeQL workflow to add `actions` as a supported language and use `autobuild` as the build mode for all languages. It also includes security-and-quality queries for better vulnerability detection.
Additional changes include replacing Go setup with Node.js setup and using Node.js version 23.x and npm caching.
Closes #340

fix(ci): bring CodeQL workflow setup up-to-date

---

server/src/data/accounts.ts

Potential fix for [https://github.com/arikkfir/greenstar/security/code-scanning/19](https://github.com/arikkfir/greenstar/security/code-scanning/19)
To fix the issue, we need to remove the redundant `|| null` from line 210. The `if (displayNameFilter)` condition already ensures that `displayNameFilter` is truthy before executing the block, so the fallback to `null` is unnecessary. This change will not alter the functionality of the code but will make it cleaner and easier to understand.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Fix code scanning alert no. 19: Useless conditional

---

.github/workflows/verify.yaml

Adjust the `verify` workflow by relocating `permissions` configuration from the workflow level to individual jobs. This aligns with the latest best practices in GitHub Actions and ensures granular permission control.

fix(ci): move GHA permissions to job level in the `verify` workflow

---

deploy/chart/files/migrations/V020__rates.sql
server/src/data/currencies.ts

Replace `rates` composite primary key of `date`, `source_currency_code` & `target_currency_code` with a unique constraint of the same columns, and a single `id` primary key.
This enables single-column primary key which is easier to manage.

chore(db): switch from composite pk to single ID and unique constraint

---

deploy/chart/files/migrations/V040__accounts.sql
deploy/chart/files/migrations/V050__transactions.sql

Ensure all column validation constraints start with the `val_` prefix.

chore(db): name column validation constraints with common prefix

---

.idea/codeStyles/Project.xml

Disable the automatic wrapping of code in JetBrains IDEs when reaching the right margin.

chore(ide): disable auto-wrap on typing in IDE

---

Taskfile.yaml
skaffold.yaml

Enable workloads running in the local `kind` cluster to have a GCP workload identity by integrating an OIDC provider with your GCP project.
To enable:
1. Ensure you are authenticated to your GCP project by running:
```shell
$ gcloud auth print-access-token
$ gcloud config get-value project
```
2. Enable GCP for the local kind cluster:
```shell
$ task enable-gcp-workload-identity-federation
```

feat(gcp): add GCP integration for local kind cluster

---

deploy/chart/files/migrations/V020__rates.sql

Incomplete change in previous commit that renamed the primary key of the `rates` table from `pk_rates` to `uq_rates`, but kept it defined as `PRIMARY KEY`.
This change finishes the job by updating it to its correct type: `UNIQUE` and adds an `id` primary key column.

fix(db): add missing PK and fix naming mismatch of UQ constraint

---

.github/workflows/verify.yaml

Use the larger GitHub Actions runner for the verify workflow to enable faster run times.

fix(ci): use large GitHub Actions runner in verify workflow

---

.github/workflows/build.yaml

Rename the pr.yaml workflow to build.yaml to better signal that it runs on both the `main` branch as well as pull requests.

chore(ci): rename pr.yaml workflow to build.yaml

---

.github/workflows/build.yaml
Taskfile.yaml
acme/src/main.ts
deploy/chart/templates/acmejob.tpl.yaml
deploy/chart/values.schema.json
deploy/chart/values.yaml
deploy/local/acme/acme.yaml
deploy/local/chart-ci-values.yaml
deploy/local/chart-local-values.yaml
scripts/download-cluster-state.sh
skaffold.yaml

Allow adding more sample tenants when installing the Helm chart, improving the developer experience. 
Custom ACME tenant files can now be placed in the `deploy/local/acme` directory, where each YAML file represents a single tenant. Each such file will be transformed into a `ConfigMap` entry upon deployment, which is read by the ACME job. In local environments, you can create files such as `deploy/local/acme/my-tenant.local.yaml` and it will be excluded from SCM given it's `.local.` string in its name.
Additional changes included are:
- GitHub Actions cluster state artifact includes more data from all namespaces
- Taskfile task `setup-tenant-helm-values-files` renamed to `setup-tenants-values-file`
- Fixed a bug in `enable-gcp-workload-identity-federation` task related to …

feat(acme): allow custom ACME tenant population

---

deploy/chart/files/migrations/V030__tenants.sql
deploy/chart/files/migrations/V040__accounts.sql
deploy/chart/files/migrations/V050__transactions.sql
deploy/chart/files/migrations/V060__scrapers.sql

Update SQL migrations to replace `TEXT` with `VARCHAR(10)` for tenant ID columns in `accounts`, `transactions`, `scrapers`, and `tenants` tables.
Add explicit constraints for primary and foreign keys to improve schema clarity and consistency. Include a non-empty check for `display_name` in `tenants`.

fix(sql): enforce tenant ID constraints and adjust foreign keys

---

deploy/chart/templates/acmejob.tpl.yaml
deploy/chart/templates/postgres.tpl.yaml
deploy/chart/templates/ratesjob.tpl.yaml
deploy/chart/templates/server.tpl.yaml

Refactor Flyway migrations to a Kubernetes job with hooks for pre-upgrade and post-install. This allows removing the init-containers in currency rates & ACME jobs that wait until PostgreSQL/server are available.
Additionally, add a PVC to the server micro-service for files upload storage.

feat(server): use Helm job to perform SQL migration
