- .github/workflows/deploy_pr_changes.yml
PR changes caused a deployment to an incorrectly named environment.
> fix(gha): fix PR deployment

- deploy/cluster/certificate.yaml
- deploy/cluster/dnsrecord.yaml
- deploy/cluster/kustomization.yaml
This change introduces the "greenstar" word into the DNS records of the application.
> fix: add greenstar to DNS record

- .github/workflows/branch_deploy.yml
- .github/workflows/pr_deploy.yml
Rename deployment workflows to better reflect their purpose.
> fix(gha): improve workflow names

- .github/workflows/pr_deploy.yml
- .idea/runConfigurations/All_Tests_in_playwright_config_ts.xml
- e2e/.gitignore
- e2e/apply-patches.sh
- e2e/codegen.ts
- e2e/package-lock.json
- e2e/package.json
- e2e/playwright.config.ts
- e2e/src/fixtures/tenant.graphql
- e2e/src/generated/graphql.ts
- frontend/package.json
- generate.sh
Add GraphQL code-generation to the end-to-end testing harness.
> feat(e2e): Add GraphQL to end-to-end tests harness

- frontend/package-lock.json
Update indirect dependencies of the frontend module.
> chore(frontend): Update dependencies

- README.md
This will be useful in the future when we will want to add future icons.
> docs(readme): Add icons resources to README.md file

- .github/workflows/build.yaml
- Taskfile-env.yaml
- Taskfile.yaml
This change better reflects the name of the flag.
> chore(backend): Rename CURRENCYAPI_KEY to CURRENCY_API_KEY

- Taskfile.yaml
- backend/internal/server/resources/account/create.go
Prevent using custom IDs when creating accounts.
> fix(backend): Remove support for custom ID during account creation

- frontend/src/components/table/transactions/Columns.tsx
- frontend/src/components/table/transactions/TransactionsTable.tsx
- frontend/src/components/tree/accounts/AccountsTree.tsx
- frontend/src/pages/TransactionsPage.tsx
- Hide transaction ID and reference ID by default
- Allow resetting transactions list to global list
> feat(frontend): Minor features to transactions list page

- .github/workflows/codeql.yml
This change adds Advanced Code Scanning configuration.
> feat(build): Create codeql.yml

- api.yaml
- backend/internal/server/resources/account/create.go
- backend/internal/server/resources/account/patch.go
- backend/internal/server/resources/account/update.go
- backend/internal/server/resources/openapi/openapi.yaml
This ensures they cannot be sent in POST requests.
> fix(api): Mark calculated API properties as read only

- backend/cmd/backend/main.go
This helps the development process without significant effect on performance.
> feat(backend): Reduce CORS pre-flights cache period

- .github/workflows/build.yaml
- Taskfile-env.yaml
- frontend/Dockerfile.frontend
- frontend/src/providers/LocaleProvider.tsx
- frontend/src/services/location_iq.ts
- skaffold.yaml
Remove the LocationIQ access key token from the source code and provide it during build time from 1Password.
> feat(frontend): Externalize LocationIQ access key

- backend/internal/server/resources/account/handler_impl.go
This changes the account creation REST endpoint to return HTTP/422 if the given ID of the parent account is not a valid UUID.
This is an initial support for validation - and an upcoming more comprehensive validation framework will follow.
> fix(backend): Return HTTP 422 when invalid parent ID provided

- frontend/src/providers/LocaleProvider.tsx
The `LocaleProvider` provider causes excessive renders for anything that relies on its locale and currency information, due to the layered approach of how it used `useEffect` tree.
This change modifies it to a single `useEffect` call which minimizes the renders.
> fix(frontend): Excessive page renders due to LocaleProvider

- Taskfile.yaml
- frontend/src/hooks/locale.tsx
- frontend/src/providers/LocaleProvider.tsx
This change strips the fractions from the account balances shown in the accounts tree in the transactions page, as it just takes up space and is not really interesting at this level.
> feat(frontend): Show rounded account balances in accounts tree

- frontend/.gitignore
This change improves the frontend Git ignore files to explicitly ignore certain patterns in the frontend root directory.
> chore(frontend): Improve Git ignore file to refer to root directory

- backend/go.mod
This change updates `go.mod` with the result of running `go mod tidy`.
> chore(backend): Sync the `go.mod` file

- go.work.sum
- scripts/generate-rest/go.mod
- scripts/generate-rest/go.sum
Update Go modules and workspace dependencies.
> fix(go): Update Go dependencies

- frontend/src/components/table/transactions/TransactionsTable.tsx
This change merges the column definitions list building into the `<TransactionsTable/>` component.
> chore(frontend): Merge transactions column definitions into table

- Taskfile.yaml
This change reorders the tasks in the Taskfile to a more reasonable ordering:
- DNS setup
- Cluster setup
- Dependencies download
- Code format
- Code generation (after code format as it invokes it)
- Deployment/development
- Helm packaging
- Testing
- Telepresence
> chore(build): Reorder Taskfile tasks

- .idea/inspectionProfiles/Project_Default.xml
- .idea/runConfigurations/backend.xml
- Taskfile.yaml
This change updates the "backend" run configuration of the JetBrains IDE to use the "backend.local.env" file.
It also instructs the IDE to suppress warnings about not checking error return value of calls to "os.Remove(...)" used in "defer" statements.
> chore(ide): Update JetBrains IDE files

- CONTRIBUTING.md
This change explains the structure of commit messages required in the project.
> docs: Elaborate on commit requirements in CONTRIBUTING.md

- deploy/chart/files/migrations/V050__transactions.sql
> fix(db): remove redundant currency constraint

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- acme/package.json
- deploy/chart/Chart.yaml
- deploy/chart/values.yaml
- e2e/package.json
- frontend/package.json
- ratesjob/package.json
- scripts/download-cluster-state.sh
- server/package.json
- skaffold.yaml
Update all GitHub and Git references to reflect the new GitHub owner after the repository has been transferred from `arikkfir` to `arikkfir-org`.
> chore(git): update references to new GitHub owner

- .github/workflows/build.yaml
- build/Taskfile-graphql.yaml
- e2e/Dockerfile
- e2e/package.json
- e2e/playwright.config.ts
- e2e/tests/dashboard.spec.ts
Update Playwright configuration:
Introduce a Dockerfile for e2e testing, enabling containerized execution of the end-to-end tests. This saves time in CI workflows currently spent on installing Playwright browser dependencies.
Additional changes:
- Adjust timeouts for improved consistency and reliability.
- Refine `dashboard.spec.ts` title validation.
> feat(e2e): containerize end-to-end tests in CI workflows

- server/src/data/data_layer.ts
Update the `NoOpDataLayer` class to add `_` prefixes to unused parameters.
> refactor(server): prefix unused function parameters with underscores

- server/src/data/data_layer.ts
- Add missing `implements` clause for the `NoOpDataLayer` class
- Move `fetchTransaction` down
- Remove unneeded DataLoader caches
> chore(server)!: miscellaneous data layer fixes
